//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentSystem.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditRentalData
    {
        public int AuditID { get; set; }
        public string Operation { get; set; }
        public Nullable<int> Rent_ID { get; set; }
        public Nullable<int> Car_ID { get; set; }
        public Nullable<int> Client_ID { get; set; }
        public Nullable<int> Service_ID { get; set; }
        public Nullable<System.DateTime> Rent_Start_Date { get; set; }
        public Nullable<System.DateTime> Rent_End_Date { get; set; }
        public Nullable<decimal> Total_Rent_Cost { get; set; }
    }
}
