//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentSystem.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarRentSystemEntities : DbContext
    {
        public CarRentSystemEntities()
            : base("name=CarRentSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuditRentalData> AuditRentalData { get; set; }
        public virtual DbSet<Brands> Brands { get; set; }
        public virtual DbSet<Car_specifications> Car_specifications { get; set; }
        public virtual DbSet<Car_Status> Car_Status { get; set; }
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<DriveUnits> DriveUnits { get; set; }
        public virtual DbSet<Engines> Engines { get; set; }
        public virtual DbSet<ManagerRents> ManagerRents { get; set; }
        public virtual DbSet<Managers> Managers { get; set; }
        public virtual DbSet<Models> Models { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Rental_data> Rental_data { get; set; }
        public virtual DbSet<RentDetails> RentDetails { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tariff> Tariff { get; set; }
        public virtual DbSet<Transmissions> Transmissions { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
