//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentSystem.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int Payment_ID { get; set; }
        public int Rent_ID { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
        public string Payment_Status { get; set; }
        public decimal Payment_Amount { get; set; }
    
        public virtual Rental_data Rental_data { get; set; }
    }
}
