//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentSystem.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentDetails
    {
        public int RentDetails_ID { get; set; }
        public Nullable<int> Rent_ID { get; set; }
        public Nullable<int> Service_ID { get; set; }
    
        public virtual Rental_data Rental_data { get; set; }
        public virtual Services Services { get; set; }
    }
}
