//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentSystem.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental_data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rental_data()
        {
            this.ManagerRents = new HashSet<ManagerRents>();
            this.Payments = new HashSet<Payments>();
            this.RentDetails = new HashSet<RentDetails>();
        }
    
        public int Rent_ID { get; set; }
        public int Car_ID { get; set; }
        public int Client_ID { get; set; }
        public Nullable<int> Service_ID { get; set; }
        public System.DateTime Rent_Start_Date { get; set; }
        public System.DateTime Rent_End_Date { get; set; }
        public Nullable<decimal> Total_Rent_Cost { get; set; }
    
        public virtual Clients Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManagerRents> ManagerRents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payments> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentDetails> RentDetails { get; set; }
        public virtual Services Services { get; set; }
    }
}
